name: 'Publish Dag'
description: 'Publish Dag to Serv-C API'
inputs:
  dag_json:
    description: 'Location of the dag JSON file to be published'
    default: 'dag.json'
  api_url:
    description: 'SERV-C API URL to publish the dag'
    default: 'https://api.servc.io'
  api_token:
    description: 'API token for authentication'
    required: true
  python_version:
    description: 'Python version to use for the action'
    default: '3.13'

runs:
  using: "composite"

  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '${{ inputs.python_version }}'
    
    - name: Install Dependencies
      run: pip install requests
    
    - name: Publish Dag
      env:
        API_URL: '${{ inputs.api_url }}'
        API_TOKEN: '${{ inputs.api_token }}'
        DAG_JSON: '${{ inputs.dag_json }}'
      run: python publish_dag.py